topic: "Reforma Tributária"
keywords:
  - "reforma tributária"
  - "imposto"
  - "tributação"
  - "reforma fiscal"
  - "carga tributária"
limits:
  twitter: 800    # Volume principal
  reddit: 200     # Complemento qualitativo
filters:
  min_length: 10
  max_length: 300
  language: "pt"
reddit:
  subreddits:
    - "brasil"
    - "politica"
    - "brasilivre"
  client_id: "${REDDIT_ID}"
  client_secret: "${REDDIT_SECRET}"
  user_agent: "${REDDIT_AGENT}"
  username: "${REDDIT_USERNAME}"
  password: "${REDDIT_PASSWORD}"
twitter:
  lang: "pt"
  place_country: "BR"
  exclude_retweets: true